kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: appleboy/drone-sftp-cache
    settings:
      server:
        from_secret: sftp_server
      port:
        from_secret: sftp_port
      username:
        from_secret: sftp_username
      password:
        from_secret: sftp_password
      path: cache
      restore: true
      mount:
        - target
  - name: check-test-build
    image: rust:1.49.0-alpine
    commands:
      - apk add --no-cache musl-dev
      - cargo check
      - cargo test
      - cargo build --release --target x86_64-unknown-linux-musl
  - name: tags
    image: alpine/git
    commands:
      - git rev-parse --short HEAD | tee .tags
  - name: rebuild-cache
    image: appleboy/drone-sftp-cache
    settings:
      server:
        from_secret: sftp_server
      port:
        from_secret: sftp_port
      username:
        from_secret: sftp_username
      password:
        from_secret: sftp_password
      path: cache
      rebuild: true
      mount:
        - target
  - name: build-docker-image
    image: plugins/docker
    settings:
      storage_driver: vfs
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      repo:
        from_secret: registry_repo
      registry:
        from_secret: registry
    when:
      branch:
        - master
      event:
        - push
